[package]
name = 'tomledit'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = "1.65.0"

[lib]
crate-type = [ 'staticlib' ]
name = 'tomledit'

[dependencies]
extendr-api = { version = "0.8.2", features = ["result_condition"] }
taplo = "0.13.2"
toml_edit = { version = "0.24.0" }

[profile.release]
codegen-units = 1
lto = true
