# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_tomledit_wrappers", use_symbols = TRUE, package_name = "tomledit")

#' @usage NULL
#' @useDynLib tomledit, .registration = TRUE
NULL

Toml <- new.env(parent = emptyenv())

Toml$new <- function() .Call(wrap__Toml__new)

Toml$parse_toml <- function(x) .Call(wrap__Toml__parse_toml, x)

Toml$read <- function(path) .Call(wrap__Toml__read, path)

Toml$write <- function(path, fmt) .Call(wrap__Toml__write, self, path, fmt)

Toml$format <- function(fmt) .Call(wrap__Toml__format, self, fmt)

Toml$format_lines <- function(fmt) .Call(wrap__Toml__format_lines, self, fmt)

Toml$insert_list <- function(x, df_as_array) .Call(wrap__Toml__insert_list, self, x, df_as_array)

Toml$remove_item <- function(key) .Call(wrap__Toml__remove_item, self, key)

Toml$get_item <- function(x) .Call(wrap__Toml__get_item, self, x)

Toml$from_toml <- function() .Call(wrap__Toml__from_toml, self)

#' @export
`$.Toml` <- function (self, name) { func <- Toml[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Toml` <- `$.Toml`


# nolint end
